services:
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./services/proxy/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./services/proxy/nginx/snippets:/etc/nginx/snippets:ro
            - ./services/proxy/certbot/conf:/etc/letsencrypt:ro
            - ./services/proxy/certbot/www:/var/www/certbot:ro
            - ./static:/var/www/html:ro

    certbot:
        image: certbot/certbot
        volumes:
            - ./services/proxy/certbot/conf:/etc/letsencrypt
            - ./services/proxy/certbot/www:/var/www/certbot

    lazy-manager:
        build: ./services/lazy-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/app-dir
        environment:
            IDLE_TIMEOUT: 10 # seconds
            PROJECT_NAME: demos
            APP_DIR: /app-dir
            PYTHONUNBUFFERED: "1"
        expose:
            - "8001"
        depends_on:
            - nginx
        restart: unless-stopped

volumes:
    postgres_data:
