services:
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./proxy/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./proxy/nginx/snippets:/etc/nginx/snippets:ro
            - ./proxy/certbot/conf:/etc/letsencrypt:ro
            - ./proxy/certbot/www:/var/www/certbot:ro
            - ./static:/var/www/html:ro

    certbot:
        image: certbot/certbot
        volumes:
            - ./proxy/certbot/conf:/etc/letsencrypt
            - ./proxy/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; docker exec demos-nginx-1 nginx -s reload; sleep 12h & wait $${!}; done;'"

    lazy-manager:
        build: ./services/lazy-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/app-dir
        environment:
            IDLE_TIMEOUT: 60 // 1 minute
            PROJECT_NAME: demos
            APP_DIR: /app-dir
            PYTHONUNBUFFERED: "1"
        expose:
            - "8001"
        depends_on:
            - nginx
        restart: unless-stopped

    db:
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
